// Copyright (c) 2019 Álvaro Ceballos
// Distributed under the Boost Software License, Version 1.0.
// See accompanying file LICENSE or copy at http://www.boost.org/LICENSE_1_0.txt

#ifndef CYNODELIC_METAFLAGS_PREPROCESSOR_DETAIL_GET_ARGUMENT_HELPERS_HPP
#define CYNODELIC_METAFLAGS_PREPROCESSOR_DETAIL_GET_ARGUMENT_HELPERS_HPP


#include <cynodelic/metaflags/config.hpp>
#include <cynodelic/metaflags/preprocessor/detail/pp_concat.hpp>


#define CYNODELIC_METAFLAGS_DETAIL_HAS_EXTRA_ARG(...) CYNODELIC_METAFLAGS_DETAIL_HAS_EXTRA_ARG_IMPL(__VA_ARGS__,CYNODELIC_METAFLAGS_DETAIL_VALUES_SEQUENCE)
#define CYNODELIC_METAFLAGS_DETAIL_HAS_EXTRA_ARG_IMPL(...) CYNODELIC_METAFLAGS_DETAIL_HAS_EXTRA_ARG_VAL(__VA_ARGS__)

#define CYNODELIC_METAFLAGS_DETAIL_HAS_EXTRA_ARG_VAL(_1,_2,N,...) N

#define CYNODELIC_METAFLAGS_DETAIL_VALUES_SEQUENCE 1,0,0

#define CYNODELIC_METAFLAGS_DETAIL_GET_ARGUMENT_IMPL_0(prs,flag,index) prs::template get<CYNODELIC_METAFLAGS_STRING_KL(flag,CYNODELIC_METAFLAGS_MAX_FLAG_STRING_LENGTH),index>()
#define CYNODELIC_METAFLAGS_DETAIL_GET_ARGUMENT_IMPL_1(prs,flag,index,deft) prs::template get<CYNODELIC_METAFLAGS_STRING_KL(flag,CYNODELIC_METAFLAGS_MAX_FLAG_STRING_LENGTH),index>(deft)


#endif // CYNODELIC_METAFLAGS_PREPROCESSOR_DETAIL_GET_ARGUMENT_HELPERS_HPP
